### ISSUE TITLE
Use ppx_expect inside of a top_level

### ISSUE THREAD

**Issue by clecat** [janestreet/ppx_expect#14]
Hello,
I am actually trying to use ppx_expect in a top_level for the project [mdx](https://github.com/realworldocaml/mdx).
But it fails with this message:
```
Error: ppx_expect: extension is disabled because the tests would be ignored (the build system didn't pass -inline-test-lib)
```
As we are using it in a top level, and not trough a build_system.
I talked a bit a about this with @diml and he proposed that we could modify ppx_expect so when it is used in a top_level, it does a simple output diff:
```
# let f output =
    print_string output;
    [%expect {| hello world |}]
  in
  f "blah";;
Exception: output doesn't match correction, got "blah" instead of "hello world"
```
Does it seems doable/acceptable ?

**Comment by diml** [comment]
Yep, that seems reasonable. Do you want to have a shot at it?

**Comment by clecat** [comment]
Thanks, I will give it a try

**Comment by jeremiedimino** [comment]
@clecat, I'm closing this issue to clear up the bug tracker. Feel free to re-open if you are still interested in this issue.
