### ISSUE TITLE
LWT example in Readme no longer works

### ISSUE THREAD

**Issue by Lupus** [janestreet/ppx_expect#20]
Readme suggests the following for Lwt:
```ocaml
module Expect_test_config
  : Expect_test_config.S with module IO = Lwt =
struct
  module IO = Lwt
  let flush () = Lwt_io.(flush stdout)
  let run = Lwt_main.run
end
```

It does not build with recent versions of ppx_expect, and the signature has changed for `Expect_test_config.S`.

**Comment by jeremiedimino** [comment]
I've updated the description internally. it should pop up on github in a few days.

**Comment by Lupus** [comment]
Cool, thanks!

чт, 25 июн. 2020 г., 18:10 Jérémie Dimino <notifications@github.com>:
