### ISSUE TITLE
Modify Doc from jbuild file to dune file

### ISSUE THREAD

**Issue by lubegasimon** [janestreet/ppx_expect#29]
Trivial: Documentation still references `jbuild` file rather than `dune` file Under [section](https://github.com/janestreet/ppx_expect#output-patterns)

**Comment by jeremiedimino** [comment]
Indeed. This is because inside Jane Street, we are still using jbuild files. We'll update the readme to have one internal facing documentation talking about jbuild files and one external facing one talking about dune files.
