### ISSUE TITLE
ppx_expect shouldn't digest files when invoked by merlin

### ISSUE THREAD

**Issue by jeremiedimino** [janestreet/ppx_expect#30]
We were looking at an issue with @voodoos where merlin wasn't working in files with `let%expect`. We boiled it down to the fact that `ppx_expect` reads the input file, using the filename specified in locations of the AST.

It seems that there is something to do on  the merlin side, but on the ppx_expect side it seems pointless to digest files when we are invoked by merlin.

**Comment by ceastlund** [comment]
Our fix for this - checking for tool name = merlin - was released with 0.15.0 some time ago.
