### ISSUE TITLE
junit output integration

### ISSUE THREAD

**Issue by kanishka-work** [janestreet/ppx_expect#33]
Have you already looked into providing a way that integrate with the junit package? If not, are there future plans to consider this?

**Comment by yminsky** [comment]
You mean the Java testing package junit? In any case, we have no such plans.

**Comment by kanishka-work** [comment]
Yes, the result format historically defined by junit: 
![Screenshot_20210910-092940](https://user-images.githubusercontent.com/1385802/132861056-0ff8bd7a-0d13-4fec-b295-74e8aa54806a.png).

Thanks for the information!
