### ISSUE TITLE
Bootstrapping problem: ppx_expect depends on ppx_driver which depends on ppx_expect

### ISSUE THREAD

**Issue by tautschnig** [janestreet/ppx_expect#7]
It seems impossible to build ppx_expect from scratch as ppx_driver depends on ppx_expect. I'm not sure whether this is a bug in ppx_expect or ppx_driver.

**Comment by hhugo** [comment]
`ppx_driver` does not depend on `ppx_expect`

**Comment by tautschnig** [comment]
https://github.com/janestreet/ppx_driver/blob/ee1518adba0ac73bb99df958dfbfe56d6f5dce04/test/omp-integration/test/jbuild#L4 suggests otherwise.

**Comment by hhugo** [comment]
What command are you trying run ? What are you trying to do ?
The jbuild you reference above is about a test. It is certainly not needed to compile & install ppx_driver.
It is known that there are cycles between janestreet packages if you try to run tests. We should address this issue at some point.

**Comment by tautschnig** [comment]
I couldn't find any build instructions, so I am just running `make`. (What I'm trying to do is build all dependencies of `ppx_sexp_conv`.)

**Comment by hhugo** [comment]
What version of jbuilder do you use ? jbuilder.1.0+beta17 was initially broken.
Try reinstalling jbuilder and then reinstall ppx_core and its dependencies.

**Comment by tautschnig** [comment]
It seems I have fallen for the same trap as elsewhere: jbuilder appears to silently ignore the missing dependencies, and it was just me having report jbuilder all of them to debug a confusing error message. Closing.
