### ISSUE TITLE
ppx_expect does not capture the output of Format.printf

### ISSUE THREAD

**Issue by Armael** [janestreet/ppx_expect#9]
ppx_expect does not seem to work with `Format`, eg `Format.printf`. The following expect test passes, printing "hello" in the terminal:

```ocaml
let%expect_test _ =
  Format.printf "hello";
[%expect {||}]
```

**Comment by Armael** [comment]
(cc @diml)

**Comment by diml** [comment]
Can you try adding `@.` at the end of the format string to force a flush?

**Comment by Armael** [comment]
Ahhhh, indeed, with a `@.` it works... I guess there's nothing particular to be done about this on ppx_expect's side?

**Comment by diml** [comment]
I submitted a change to flush `Format.{std,err}_formatter` in our internal review system. I'll backport it to the v0.11 branch once it's released.

**Comment by Armael** [comment]
Thank you!

**Comment by diml** [comment]
Note: in the meantime you can also override the `Expect_test_config` module that's in scope:

```ocaml
module Expect_test_config = struct
  include Expect_test_config
  let flush () = Format.pp_print_flush Format.std_formatter (); flush ()
end
```
